spring.application.name=visto
spring.datasource.url=jdbc:postgresql://localhost:5432/visto
spring.datasource.username=visto
spring.datasource.password=visto123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
